variables:
  OS_CHOICES: "['linux', 'darwin', 'windows', 'all']"
  ARCH_CHOICES: "['amd64', 'arm64']"
  DEFAULT_BRANCH: "main"
  OS: "linux"
  ARCH: "amd64"
  BUILDS_DIR: "bin"
  APP: "kbot"

stages:
  - vars
  - test
  - build
  - image
  
vars-job:
  stage: vars
  script:
    - echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> build.env
    - echo "BUILD_URL=$(echo "${CI_REPOSITORY_URL}" | sed -E "s|https:\/\/.*@(.*)\.git|\1|")" >> build.env
  artifacts:
    reports:
      dotenv: build.env

test-job:
  stage: test
  script:
    - go test -v

build-job:
  stage: build
  script:
    - gofmt -s -w ./
    - go get
    - CGO_ENABLED=0 GOOS=${OS} GOARCH=${ARCH} go build -v -o ${BUILD_DIR}/${APP} -ldflags "-X=${BUILD_URL}$/cmd.appVersion=${VERSION}"

image-job:
  stage: image
  script:
    - 
    - echo $GITHUB_TOKEN_PSW | docker login ghcr.io -u $GITHUB_TOKEN_USR --password-stdin
    - make $OS $ARCH image push
    - docker logout
