variables:
  OS_CHOICES: "['linux', 'darwin', 'windows', 'all']"
  ARCH_CHOICES: "['amd64', 'arm64']"
  DEFAULT_BRANCH: "main"
  REPO_URL: "https://gitlab.com/rusnipizda/kbot"

parameters:
  OS:
    type: string
    default: 'all'
    description: 'Pick OS'
    values: $OS_CHOICES
  ARCH:
    type: string
    default: 'amd64'
    description: 'Pick ARCH'
    values: $ARCH_CHOICES
    
stages:
  - clone
  - test
  - build
  - image
  - login
  - push

kbot:
  clone:
    stage: clone
    script:
      - echo "CLONE REPOSITORY"
      - git clone -b $BRANCH $REPO

  test:
    stage: test
    script:
      - echo "TEST EXECUTION STARTED"
      - make test

  build:
    stage: build
    script:
      - echo "BINARY BUILD EXECUTION STARTED FOR $OS ($ARCH)
      - make $OS $ARCH

  image:
    stage: image
    script:
      - echo "IMAGE BUILD EXECUTION STARTED FOR $OS ($ARCH)
      - make image-$OS $ARCH

  login:
    stage: login
    script:
      - echo "LOGIN TO IMAGE REGISTRY"
      - echo $GITHUB_TOKEN_PSW | docker login ghcr.io -u $GITHUB_TOKEN_USR --password-stdin

  push:
    stage: push
    script:
      - echo "PUSHING IMAGE STARTED"
      - make $OS $ARCH image push
    after_script:
      - docker logout
