# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: "lawrider"
  tag: "v1.0.2-a0a12e7"
  arch: amd64
secret:
  name: "kbot"
  key: "token"
  env: "TELE_TOKEN"
