# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
<<<<<<< HEAD
  repository: "lawrider"
  tag: "v1.0.2-a0a12e7"
  arch: amd64
=======
  registry: "ghcr.io"
  #repository: "lawrider"
  #repository: "LawRider/kbot"
  pullPolicy: IfNotPresent
  tag: "v1.0.4-5e18a4f"
  os: linux
  arch: amd64
  parameter: go
  
>>>>>>> 420b54f (Change Docker Hub to GitHub Container Registry)
secret:
  name: "kbot"
  key: "token"
  env: "TELE_TOKEN"
